import React, { useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ExternalLink, FileText, Code, Image as ImageIcon, History } from 'lucide-react';

interface Asset {
  id: string;
  name: string;
  type: 'PAGE' | 'DOC' | 'IMAGE' | 'CODE';
  status: 'DRAFT' | 'PUBLISHED';
  createdAt: string;
  agentName: string;
  lineageId: string;
}

const mockAssets: Asset[] = [
  { id: '1', name: 'Landing Page v1', type: 'PAGE', status: 'DRAFT', createdAt: '2026-03-30', agentName: 'Hacker-1', lineageId: 'run-882' },
  { id: '2', name: 'GTM Strategy Doc', type: 'DOC', status: 'PUBLISHED', createdAt: '2026-03-29', agentName: 'Growth Hacker', lineageId: 'run-741' },
  { id: '3', name: 'Auth Component React', type: 'CODE', status: 'DRAFT', createdAt: '2026-03-30', agentName: 'Builder', lineageId: 'run-912' },
];

export const AssetGallery = () => {
  const [filter, setFilter] = useState('ALL');

  const icons = {
    PAGE: <ExternalLink className="w-4 h-4" />,
    DOC: <FileText className="w-4 h-4" />,
    CODE: <Code className="w-4 h-4" />,
    IMAGE: <ImageIcon className="w-4 h-4" />,
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold tracking-tight">Assets & Artifacts</h2>
        <Tabs defaultValue="ALL" onValueChange={setFilter}>
          <TabsList>
            <TabsTrigger value="ALL">All</TabsTrigger>
            <Tokens value="PAGE">Pages</Tokens>
            <TabsTrigger value="DOC">Docs</TabsTrigger>
            <TabsTrigger value="CODE">Code</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {mockAssets.map((asset) => (
          <Card key={asset.id} className="group hover:shadow-md transition-all">
            <CardHeader className="pb-2">
              <div className="flex justify-between items-start">
                <div className="p-2 bg-slate-100 rounded-md">
                  {icons[asset.type]}
                </div>
                <Badge variant={asset.status === 'PUBLISHED' ? 'default' : 'secondary'}>
                  {asset.status}
                </Badge>
              </div>
              <CardTitle className="text-lg mt-3">{asset.name}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center text-xs text-muted-foreground space-x-2 mb-4">
                <History className="w-3 h-3" />
                <span>Generated by <strong>{asset.agentName}</strong></span>
              </div>
              <div className="aspect-video bg-slate-50 rounded-md border border-dashed flex items-center justify-center text-xs text-slate-400 italic">
                Preview coming soon...
              </div>
            </CardContent>
            <CardFooter className="flex gap-2">
              <Button variant="outline" size="sm" className="w-full text-xs">View Lineage</Button>
              <Button size="sm" className="w-full text-xs">Preview Draft</Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
};

function Tokens({ value, children }: { value: string, children: React.ReactNode }) {
    return <TabsTrigger value={value}>{children}</TabsTrigger>
}
