'use client';

import React, { useState } from 'react';
import { ExternalLink, FileText, Code, Image as ImageIcon, History } from 'lucide-react';

interface Asset {
  id: string;
  name: string;
  type: 'PAGE' | 'DOC' | 'IMAGE' | 'CODE';
  status: 'DRAFT' | 'PUBLISHED';
  createdAt: string;
  agentName: string;
  lineageId: string;
}

const mockAssets: Asset[] = [
  { id: '1', name: 'Landing Page v1', type: 'PAGE', status: 'DRAFT', createdAt: '2026-03-30', agentName: 'Hacker-1', lineageId: 'run-882' },
  { id: '2', name: 'GTM Strategy Doc', type: 'DOC', status: 'PUBLISHED', createdAt: '2026-03-29', agentName: 'Growth Hacker', lineageId: 'run-741' },
  { id: '3', name: 'Auth Component React', type: 'CODE', status: 'DRAFT', createdAt: '2026-03-30', agentName: 'Builder', lineageId: 'run-912' },
];

export const AssetGallery = () => {
  const [filter, setFilter] = useState('ALL');

  const icons = {
    PAGE: <ExternalLink className="h-4 w-4" />,
    DOC: <FileText className="h-4 w-4" />,
    CODE: <Code className="h-4 w-4" />,
    IMAGE: <ImageIcon className="h-4 w-4" />,
  };

  return (
    <div className="space-y-6 p-6 sm:p-8 lg:p-10">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h2 className="text-3xl font-extrabold tracking-[-0.03em]">Assets & Artifacts</h2>
          <p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">
            Review generated pages, documents, code, and previews with a lighter enterprise gallery treatment.
          </p>
        </div>
        <div className="flex gap-2 rounded-full border border-indigo-100 bg-indigo-50/80 p-1">
          {['ALL', 'PAGE', 'DOC', 'CODE'].map((value) => (
            <button
              key={value}
              type="button"
              onClick={() => setFilter(value)}
              className={`rounded-full px-4 py-2 text-sm font-medium transition-all duration-200 ${
                filter === value ? 'bg-white text-slate-900 shadow-soft' : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              {value === 'ALL' ? 'All' : value === 'PAGE' ? 'Pages' : value === 'DOC' ? 'Docs' : 'Code'}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {mockAssets.filter((asset) => filter === 'ALL' || asset.type === filter).map((asset) => (
          <section key={asset.id} className="dashboard-card group p-5">
            <div className="pb-2">
              <div className="flex items-start justify-between">
                <div className="rounded-xl bg-indigo-50 p-3 text-indigo-600">
                  {icons[asset.type]}
                </div>
                <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${asset.status === 'PUBLISHED' ? 'bg-brand-gradient text-white shadow-glow' : 'bg-slate-100 text-slate-700'}`}>
                  {asset.status}
                </span>
              </div>
              <h3 className="mt-3 text-lg font-semibold">{asset.name}</h3>
            </div>
            <div>
              <div className="mb-4 flex items-center space-x-2 text-xs text-muted-foreground">
                <History className="h-3 w-3" />
                <span>Generated by <strong>{asset.agentName}</strong></span>
              </div>
              <div className="flex aspect-video items-center justify-center rounded-2xl border border-dashed border-indigo-100 bg-gradient-to-br from-indigo-50 to-white text-xs italic text-slate-400">
                Preview coming soon...
              </div>
            </div>
            <div className="flex gap-2 pt-4">
              <button type="button" className="w-full rounded-full border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 transition-colors hover:bg-slate-50">
                View Lineage
              </button>
              <button type="button" className="w-full rounded-full bg-brand-gradient px-3 py-2 text-xs font-semibold text-white shadow-glow transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lift">
                Preview Draft
              </button>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};
